model_name_or_path: ../Llama-3.2-3B-Instruct
adapter_name_or_path: saves/llama-3.2-3b_C/
output_dir: ./outputs/C_val

stage: sft
do_predict: true
finetuning_type: lora

eval_dataset: C_val
dataset_dir: ./prompts/
template: llama3
cutoff_len: 4096
overwrite_cache: true

preprocessing_num_workers: 16
overwrite_output_dir: true
per_device_eval_batch_size: 4
predict_with_generate: true

temperature: 0.1
top_p: 1
top_k: 200
