model_name_or_path: ../Llama-3.2-3B-Instruct
output_dir: saves/llama-3.2-3b_A/

stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 16

dataset: A_train
dataset_dir: ./prompts/
template: llama3
cutoff_len: 4096
overwrite_cache: true

preprocessing_num_workers: 16
logging_steps: 10
plot_loss: true
overwrite_output_dir: true
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000
val_size: 0.01
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 200
save_steps: 200
